version: '3'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      # API port
      - "9997:9997"
      # RTSP port
      - "8554:8554"
      # RTMP port
      - "1935:1935"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    environment:
      - MTX_PROTOCOLS=tcp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
