apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-tcp
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 9997
      targetPort: 9997
      protocol: TCP
      name: tcp-9997
    - port: 8554
      targetPort: 8554
      protocol: TCP
      name: tcp-8554
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: tcp-1935
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
